### ISSUE TITLE
Invalid statistics when filtered

### ISSUE THREAD

**Issue by iasai1** [SoftwareAG/cumulocityr#2]
I've noticed an issue when applying filters to inventory requests

For example, if i go to {{url}}/inventory/managedObjects , statistics will be like this: 
```json
"statistics": {
        "totalPages":11,
        "currentPage": 1,
        "pageSize": 5
    },
```
Which is how it should be.

However, if apply a filter, like {{url}}/inventory/managedObjects?fragmentType=c8y_IsDevice , the statistics would look like this:
```json
"statistics": {
        "currentPage": 1,
        "pageSize": 5
    },
```
Same would happen to any other filter.
To be clear, there are actually multiple pages in the response I'm getting.

Also, if I query a device measurements, statistics would always look like this:
```json
"statistics": {
        "totalPages": null,
        "currentPage": 1,
        "pageSize": 5
    },
```
In the documentation it's the same issue, with no explanation.

Is there any work around for now to know how many pages there are? It is extremely inconvenient

**Comment by dbolotov** [comment]
Hi,

Thank you for raising this issue, we see what you mean. While this does happen in the R package, the behavior seems to exist in the Cumulocity API itself, outside of R.

Can you please request support with Cumulocity directly, through your tenant?
